kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
  labels:
    app: blockchain
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-premium
